version: '3'
services:
  homeassistant:
    container_name: homeassistant-debug
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PYTHONPATH=/config/custom_components